server:
  port: 9090

spring:
  application:
    name: "stack-exchange-searcher"

stackexchange:
  api:
    url: https://api.stackexchange.com/2.2/search
  request:
    order: desc
    sort: activity
    site: stackoverflow
    filter: "!.Fjs-H6VybJDO2vVwuF_LVT82Icu6"
    key: "NPfsSxYYJquIDVOlb2z*lw(("
    accessToken: "ppUOASObhfE(*GyBRjQAeg))"

hystrix:
  command:
    searchQuestionsByTitle:
      execution:
        timeout.enabled: true
        isolation.thread.timeoutInMilliseconds: 5000
      fallback:
        enabled: true
        isolation.semaphore.maxConcurentRequests: 20
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 10
        sleepWindowInMilliseconds: 7
        errorThresholdPercentage: 75
      metrics:
        rollingStats.timeInMilliseconds: 15000
        rollingStats.numBuckets: 5
  threadpool:
    searchQuestionsByTitleThreadPool:
      coreSize: 30
      maxQueueSize: 10

logging:
  file: searcher.log
  level:
    root: WARN
    wombatukun.tests.test10.api: DEBUG
    com.netflix.config.sources.URLConfigurationSource: ERROR

